# Generated by Django 5.0.4 on 2024-05-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_Catagory',
            fields=[
                ('cat_Id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('description_tittle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('description_tittle1', models.CharField(max_length=100)),
                ('description1', models.TextField()),
                ('description_tittle2', models.CharField(max_length=100)),
                ('description2', models.TextField()),
                ('medicine_company', models.CharField(max_length=100)),
                ('medicine_company_logo', models.ImageField(upload_to='images')),
                ('medicine_image', models.ImageField(upload_to='images')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_commerce.medicine_catagory')),
            ],
        ),
    ]
