# Generated by Django 5.0.4 on 2024-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Powder', 'Powder'), ('Injection', 'Injection'), ('Saline', 'Saline')], default='Tablet', max_length=10)),
            ],
        ),
    ]
