# Generated by Django 5.0.4 on 2024-05-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0002_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Medicine_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_commerce.medicine_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine_type',
            name='medicine_type',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Powder', 'Powder'), ('Injection', 'Injection'), ('Saline', 'Saline')], default=None, max_length=10),
        ),
    ]
