# Generated by Django 5.0.4 on 2024-05-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0003_medicine_medicine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='Medicine_type',
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Powder', 'Powder'), ('Injection', 'Injection'), ('Saline', 'Saline')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
