# Generated by Django 5.0.4 on 2024-05-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0005_alter_medicine_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine_type',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='description_tittle',
            new_name='description_title',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='description_tittle1',
            new_name='description_title1',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='description_tittle2',
            new_name='description_title2',
        ),
    ]
