# Generated by Django 5.0.4 on 2024-05-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
