# Generated by Django 5.0.4 on 2024-05-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0009_remove_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='unit_price_per_piece',
            new_name='price',
        ),
    ]
