# Generated by Django 5.0.4 on 2024-05-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0015_order_order_id_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
