# Generated by Django 5.0.4 on 2024-05-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0018_remove_order_order_id_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='E_commerce.CartItem', to='E_commerce.medicine'),
        ),
    ]
