# Generated by Django 5.0.4 on 2024-05-03 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0019_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
