# Generated by Django 5.0.4 on 2024-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0022_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expire_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
