# Generated by Django 5.0.4 on 2024-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blog_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='author_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
