# Generated by Django 5.0.4 on 2024-05-04 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sequrity', '0005_ownerprofile_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('house_number', models.CharField(max_length=100)),
                ('road_number', models.CharField(max_length=100)),
                ('block_number', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('special_identification', models.CharField(blank=True, max_length=200)),
                ('house_type', models.CharField(max_length=100)),
                ('rental_amount', models.IntegerField()),
                ('size', models.IntegerField()),
                ('bedrooms', models.IntegerField(choices=[(1, '1 Bedroom'), (2, '2 Bedrooms'), (3, '3 Bedrooms')])),
                ('service_charge', models.IntegerField()),
                ('facility1', models.CharField(max_length=100)),
                ('facility2', models.CharField(blank=True, max_length=100, null=True)),
                ('facility3', models.CharField(blank=True, max_length=100, null=True)),
                ('facility4', models.CharField(blank=True, max_length=100, null=True)),
                ('floor_number', models.IntegerField()),
                ('image1', models.ImageField(upload_to='room_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_system.location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_system.roomcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('renter_image', models.ImageField(upload_to='booking_images/')),
                ('nid_image', models.ImageField(upload_to='booking_images/')),
                ('total_member', models.IntegerField()),
                ('booking_status', models.CharField(choices=[('accept', 'Accepted'), ('reject', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('booking_id', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sequrity.userprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_system.room')),
            ],
        ),
    ]
