# Generated by Django 5.0.4 on 2024-05-06 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
