# Generated by Django 5.0.4 on 2024-06-08 10:58

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0005_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='0,0', max_length=100),
        ),
    ]
