# Generated by Django 5.0.4 on 2024-06-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0007_alter_room_geolocation'),
    ]

    operations = [
    ]
