# Generated by Django 5.0.4 on 2024-06-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0008_fix_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
