# Generated by Django 5.0.4 on 2024-06-15 08:05

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0010_remove_room_latitude_remove_room_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='POINT(0.0 0.0)', max_length=100),
        ),
    ]
