# Generated by Django 5.0.4 on 2024-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0011_alter_room_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='room',
            name='location_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Location Link'),
        ),
    ]
