# Generated by Django 5.0.4 on 2024-06-15 09:23

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0012_remove_room_geolocation_room_location_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='location_link',
        ),
        migrations.AddField(
            model_name='room',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='0,0', max_length=100),
        ),
    ]
