# Generated by Django 5.0.4 on 2024-06-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0016_alter_room_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
