# Generated by Django 5.0.4 on 2024-06-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0017_remove_room_geolocation_room_latitude_room_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
        migrations.AlterField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
    ]
