# Generated by Django 5.0.4 on 2024-06-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0019_remove_room_latitude_remove_room_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='room',
            name='maplink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
