# Generated by Django 5.0.4 on 2024-06-15 18:57

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0020_remove_room_geolocation_room_maplink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='maplink',
        ),
        migrations.AddField(
            model_name='room',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='0.0,0.0', max_length=100),
        ),
    ]
