# Generated by Django 5.0.4 on 2024-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0021_remove_room_maplink_room_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
