# Generated by Django 5.0.4 on 2024-06-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_system', '0022_room_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image4',
        ),
        migrations.AddField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='room_videos/'),
        ),
    ]
