# Generated by Django 5.0.4 on 2024-05-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=100, unique=True)),
                ('joining_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff'), ('Room Cleaners', 'Room Cleaners'), ('Servants', 'Servants'), ('Accountant', 'Accountant'), ('Receptionist', 'Receptionist')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
            ],
        ),
    ]
