# Generated by Django 5.0.4 on 2024-05-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaffManagement', '0002_remove_staff_password_remove_staff_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
    ]
