# Generated by Django 5.0.4 on 2024-05-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffManagement', '0004_staff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='leaving_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
