# Generated by Django 5.0.4 on 2024-05-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffManagement', '0005_staff_leaving_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='leaving_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
