# Generated by Django 5.0.4 on 2024-05-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffManagement', '0006_alter_staff_leaving_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='on_duty',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
