# Generated by Django 5.0.4 on 2024-04-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sequrity', '0003_ownerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
