# Generated by Django 5.0.4 on 2024-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sequrity', '0004_remove_ownerprofile_password_ownerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='registration_status',
            field=models.CharField(choices=[('reject', 'Reject'), ('accept', 'Accept'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
