# Generated by Django 5.0.4 on 2024-06-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sequrity', '0006_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='profile_image',
            field=models.ImageField(default=None, upload_to='profile_images/'),
        ),
    ]
